---
output: rmarkdown::github_document
---

`bismer` : Generate Shakespearean insults

Inspired by Dr. Vicky Forster (<a href="https://twitter.com/vickyyyf">@vickyyyf</a>) : <https://twitter.com/vickyyyf/status/846028898152431618> and requested by Jeff Hollister (<a href="https://twitter.com/jhollist">@jhollist</a>).

The following functions are implemented:

- `insult`: Generate a Shakespearean insult

The `insult()` function is aliased to 

- `gehornian`
- `híenan`
- `misgrétan`
- `scendan`

for those who want to go "all-in" on the Shakespeare thing.

### Installation

```{r eval=FALSE}
devtools::install_github("hrbrmstr/bismer")
```

```{r message=FALSE, warning=FALSE, error=FALSE, include=FALSE}
options(width=120)
```

### Usage

```{r message=FALSE, warning=FALSE, error=FALSE}
library(bismer)

# current verison
packageVersion("bismer")

purrr::walk(1:10, ~print(insult()))

purrr::walk(1:10, ~print(insult(thou=FALSE)))

purrr::walk(1:10, ~print(insult(sentence=TRUE)))

purrr::walk(1:10, ~print(insult(sentence=TRUE, exclaim=FALSE)))
```
